name: atmos_tendarser_2
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  async: ^2.8.2
  atmos_binary_buffer: ^0.16.6
  atmos_database: ^0.16.2
  atmos_logger: ^0.16.1
  ffi: ^1.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  html: ^0.15.0
  intl: ^0.17.0
  meta: ^1.7.0
  source_span: ^1.8.1
  sqlite3: ^1.5.1
  stream_channel: ^2.1.0
  web_socket_channel: ^2.1.0
  yaml: ^3.1.0

dev_dependencies:
  atmos_lints: ^0.16.1

flutter:
  uses-material-design: true
  generate: true
